use_frameworks!

source 'https://github.com/morapelker/tedooo-pod-repo.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'TedoooProductGallery_Example' do
  pod 'TedoooProductGallery', :path => '../'

  target 'TedoooProductGallery_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
